import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const PlusJakartaSans1 = localFont({
  src: "./fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
})

const PlusJakartaSans2 = localFont({
  src: "./fonts/PlusJakartaSans-VariableFont_wght.ttf",  
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PlusJakartaSans1.variable} ${PlusJakartaSans2.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
